### ISSUE TITLE
!send reply latest

### ISSUE THREAD

**Issue by jcserv** [white-van/WVAnonBot#34]
This command should reply to the latest message.

**Comment by CometWhoosh** [comment]
I like the level of convenience that this would introduce for users. However, I think that it might cause some unexpected behaviour. If someone tries to reply to the latest message, and then someone else sends a message in the chat, the latest message would change, and so the person would end up replying to the wrong message.

**Comment by jcserv** [comment]
good point, what do you think of showing a preview of the message that they're replying to?
also this could be applied to the normal reply

**Comment by CometWhoosh** [comment]
I think that would be a great feature, but I'm not sure how we would implement it using the current method for replies. We only get input from the user once they send the reply, so we would only know which message they want to reply to after they send it.

Of course, we could just have them DM the bot with the id of the message they're replying to, and then have them DM it again with their reply. This would let us know what message they want to reply to so that we can show a preview before they send off their reply. However, I feel like that may make the process a bit complicated.
